# Basic snap definition
name: orbit
version: git
summary: A simple telemetry system to monitor your remote applications
description: |
  Keep an eye on your applications.
  Monitoring your remote installed applications wasn't this easy before.
  Install the Orbit Server on a server of your choice.
  Add an Orbit Client to your application.
  That's it we will now store the information for you.
  Install instruction/Help: https://github.com/glenndehaan/orbit#install
license: MIT

# Snap state
confinement: strict
grade: stable

# Snap base image
base: core18

# Snap architectures
architectures:
  - build-on: amd64

# Define snap build parts
parts:
  node:
    plugin: dump
    source: https://nodejs.org/dist/latest-v8.x/node-v8.17.0-linux-x64.tar.xz
    stage:
      - bin
      - include
      - lib
  orbit:
    after: [node]
    plugin: nil
    source: .
    override-build: |
      npm config set unsafe-perm true
      npm install
      npm rebuild
      npm run build
      cp -R . $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - g++
      - make

# Define all snap commands/services
apps:
  orbit:
    command: bin/node $SNAP/app/bundle.js
    plugs:
      - network
      - network-bind
  orbit-server:
    command: bin/node $SNAP/app/bundle.js server
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
